import Link from 'next/link';
import {ArrowUpRight, ArrowRight, Radio, Users, Terminal, FolderGit2, MessageSquare, ShieldCheck, ChevronRight, Braces, Check} from 'lucide-react';
import {Brand} from '@/components/brand';
import {FeatureCard} from '@/components/feature-card';
import {EditorPreview} from '@/components/editor-preview';
const features=[
  {icon:Radio,title:'In sync. In real time.',description:'A shared editor designed for incremental updates and conflict-free collaboration.',label:'01 / COLLABORATION'},
  {icon:Users,title:'One editor. Your whole team.',description:'Bring collaborators into the same workspace, with presence and shared context.',label:'02 / MULTI-USER'},
  {icon:Terminal,title:'From idea to output.',description:'Run JavaScript and Python through a separately configured, isolated execution service.',label:'03 / EXECUTION'},
  {icon:FolderGit2,title:'A home for every project.',description:'Organize files, save your work, and return to the workspace where you left off.',label:'04 / WORKSPACES'},
  {icon:MessageSquare,title:'Keep the conversation close.',description:'Discuss a tricky function or your next idea in chat alongside your code.',label:'05 / TEAM CHAT'},
  {icon:ShieldCheck,title:'Share with intention.',description:'Private workspaces, expiring invites, and distinct Owner, Editor, and Viewer roles.',label:'06 / ACCESS CONTROL'},
];
export default function Home(){return <><header className="site-header"><div className="container nav"><Brand/><nav aria-label="Main navigation"><a href="#features">Features</a><a href="#how-it-works">How it works</a><a href="#stack">Built for developers</a></nav><div className="nav-actions"><Link href="/login" className="sign-in">Sign in</Link><Link href="/register" className="button button-small">Start coding <ArrowUpRight size={15}/></Link></div></div></header>
  <main><section className="hero container"><div className="hero-glow"/><div className="eyebrow"><span className="live-dot"/> YOUR IDE. OUR SHARED SPACE. <ChevronRight size={13}/></div><h1>Code together.<br/><span>Build together.</span></h1><p className="hero-subtitle">A real-time collaborative code editor for developers to<br className="desktop-break"/> write, share, and debug code together.</p><div className="hero-actions"><Link href="/register" className="button">Start coding <ArrowRight size={17}/></Link><Link href="/dashboard" className="button button-secondary"><FolderGit2 size={17}/> Create workspace</Link></div><div className="hero-notes"><span><Check size={13}/> Six editing languages</span><span><Check size={13}/> Built for collaboration</span><span><Check size={13}/> Your code, your workspace</span></div><EditorPreview/><div className="preview-disclaimer">An interface preview of what we’re building. Authentication and live workspaces arrive in the next phases.</div></section>
  <section className="stack-strip" id="stack"><div className="container"><span>BUILT ON A SOLID FOUNDATION</span><div><Braces size={18}/> Next.js <i/> TypeScript <i/> PostgreSQL <i/> Prisma <i/> Monaco <i/> Socket.IO</div></div></section>
  <section className="container features" id="features"><div className="section-heading"><div><span className="section-kicker">LESS FRICTION. MORE BUILDING.</span><h2>Everything you need to<br/>find your flow. Together.</h2></div><p>A focused space for pair programming,<br/>learning together, and turning ideas into code.</p></div><div className="feature-grid">{features.map(f=><FeatureCard key={f.title} {...f}/>)}</div></section>
  <section className="container how-section" id="how-it-works"><div className="section-heading"><div><span className="section-kicker">FROM HELLO TO HELLO WORLD</span><h2>Great work starts with a connection.</h2></div></div><div className="steps"><article><span>01</span><h3>Create your workspace</h3><p>Pick a name and a language. Give your next idea a place to grow.</p></article><article><span>02</span><h3>Bring someone along</h3><p>Share an invite and choose the access your collaborators need.</p></article><article><span>03</span><h3>Build something together</h3><p>Edit, discuss, and explore solutions in one shared environment.</p></article></div></section>
  <section className="container"><div className="cta"><div className="section-kicker">YOUR NEXT IDEA DESERVES COMPANY</div><h2>Make room for better code.</h2><p>A little less switching tabs. A lot more building together.</p><Link href="/register" className="button">Create your workspace <ArrowUpRight size={17}/></Link></div></section></main><footer className="container footer"><Brand/><span>A shared space for people who build.</span><span>CodeSync · Built with TypeScript</span></footer></>;}
