import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import { z, ZodError } from 'zod';
import { Prisma } from '@prisma/client';
import { config } from './config.js';
import { db } from './db.js';
import { requireAuth,issueSession,publicUser,hashToken,token,cookieOptions } from './auth.js';
import { HttpError,membership } from './permissions.js';
import { registerSchema,loginSchema,workspaceSchema,fileSchema,filename,messageSchema,starters } from './validation.js';
import { notifyFiles,io,revokeAccess } from './realtime.js';
import { flushDocument,loadDocument,discardDocuments } from './documents.js';
import { execute } from './execution.js';
export function createApp() {
  const app=express();app.set('trust proxy',1);
  app.use(helmet(),cors({origin:config.WEB_ORIGIN,credentials:true}),express.json({limit:'300kb'}),cookieParser());
  app.use('/api',rateLimit({windowMs:60_000,limit:200,standardHeaders:'draft-8',legacyHeaders:false}));
  app.use((req,res,next)=>{if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin!==config.WEB_ORIGIN){res.status(403).json({error:'Request origin is not allowed.'});return;}next();});
  app.get('/health',async(_req,res)=>{await db.$queryRaw`SELECT 1`;res.json({status:'ok'});});
  const authLimit=rateLimit({windowMs:15*60_000,limit:30,standardHeaders:'draft-8',legacyHeaders:false});
  app.post('/api/auth/register',authLimit,async(req,res)=>{const data=registerSchema.parse(req.body);const passwordHash=await bcrypt.hash(data.password,12);const user=await db.user.create({data:{username:data.username,email:data.email,passwordHash},select:publicUser});await issueSession(res,user.id);res.status(201).json(user);});
  app.post('/api/auth/login',authLimit,async(req,res)=>{const data=loginSchema.parse(req.body);const user=await db.user.findUnique({where:{email:data.email}});const fallback='$2b$12$R9h/cIPz0gi.URNNX3kh2OPST9/PgBkqquzi.Ss7KIUgO2t0jWMUW';const valid=await bcrypt.compare(data.password,user?.passwordHash||fallback);if(!user||!valid)throw new HttpError(401,'Email or password is incorrect.');await issueSession(res,user.id);const {passwordHash,...safe}=user;res.json(safe);});
  app.post('/api/auth/logout',async(req,res)=>{if(req.cookies.codesync_session)await db.session.deleteMany({where:{id:hashToken(req.cookies.codesync_session)}});res.clearCookie('codesync_session',cookieOptions);res.status(204).end();});
  app.use('/api',requireAuth);
  app.get('/api/auth/me',(req,res)=>res.json(req.user));
  app.patch('/api/auth/me',async(req,res)=>{const data=z.object({username:z.string().trim().min(2).max(32)}).parse(req.body);res.json(await db.user.update({where:{id:req.user.id},data,select:publicUser}));});
  app.get('/api/workspaces',async(req,res)=>{const members=await db.workspaceMember.findMany({where:{userId:req.user.id},orderBy:{lastOpenedAt:'desc'},include:{workspace:{include:{owner:{select:{id:true,username:true}},_count:{select:{members:true,files:true}}}}}});res.json(members.map(m=>({...m.workspace,role:m.role,lastOpenedAt:m.lastOpenedAt})));});
  app.post('/api/workspaces',async(req,res)=>{const data=workspaceSchema.parse(req.body);const initial=starters[data.language];const workspace=await db.workspace.create({data:{...data,ownerId:req.user.id,members:{create:{userId:req.user.id,role:'OWNER'}},files:{create:[{...initial,type:'FILE'},{name:'README.md',type:'FILE',content:`# ${data.name}\n\nBuilt together with CodeSync.\n`}]}}});res.status(201).json(workspace);});
  app.post('/api/invites/join',async(req,res)=>{const raw=z.object({token:z.string().min(20).max(100)}).parse(req.body).token;const invite=await db.workspaceInvite.findUnique({where:{token:hashToken(raw)}});if(!invite||invite.expiresAt<new Date())throw new HttpError(410,'This invite is invalid or expired. Ask the owner for a new link.');await db.workspaceMember.upsert({where:{workspaceId_userId:{workspaceId:invite.workspaceId,userId:req.user.id}},create:{workspaceId:invite.workspaceId,userId:req.user.id,role:invite.role},update:{lastOpenedAt:new Date()}});res.json({workspaceId:invite.workspaceId});});
  app.get('/api/workspaces/:id',async(req,res)=>{const id=String(req.params.id);const member=await membership(id,req.user.id);const workspace=await db.workspace.findUnique({where:{id},include:{owner:{select:{id:true,username:true}},members:{include:{user:{select:{id:true,username:true,avatar:true}}}}}});await db.workspaceMember.update({where:{workspaceId_userId:{workspaceId:id,userId:req.user.id}},data:{lastOpenedAt:new Date()}});res.json({...workspace,role:member.role});});
  app.patch('/api/workspaces/:id',async(req,res)=>{const id=String(req.params.id);await membership(id,req.user.id,false,true);const data=workspaceSchema.pick({name:true}).parse(req.body);res.json(await db.workspace.update({where:{id},data}));});
  app.delete('/api/workspaces/:id',async(req,res)=>{const id=String(req.params.id);await membership(id,req.user.id,false,true);await revokeAccess(id);const files=await db.file.findMany({where:{workspaceId:id},select:{id:true}});await discardDocuments(files.map(f=>f.id));await db.workspace.delete({where:{id}});res.status(204).end();});
  app.post('/api/workspaces/:id/invites',async(req,res)=>{const id=String(req.params.id);await membership(id,req.user.id,false,true);const {role}=z.object({role:z.enum(['EDITOR','VIEWER']).default('EDITOR')}).parse(req.body);const raw=token();const expiresAt=new Date(Date.now()+24*3600*1000);await db.workspaceInvite.create({data:{workspaceId:id,invitedBy:req.user.id,role,token:hashToken(raw),expiresAt}});res.status(201).json({url:`${config.WEB_ORIGIN}/join/${raw}`,expiresAt,role});});
  app.patch('/api/workspaces/:id/members/:userId',async(req,res)=>{const id=String(req.params.id),userId=String(req.params.userId);await membership(id,req.user.id,false,true);const member=await membership(id,userId);if(member.role==='OWNER')throw new HttpError(422,'The workspace owner cannot be demoted.');const {role}=z.object({role:z.enum(['EDITOR','VIEWER'])}).parse(req.body);await db.workspaceMember.update({where:{workspaceId_userId:{workspaceId:id,userId}},data:{role}});await revokeAccess(id,userId);res.json({role});});
  app.delete('/api/workspaces/:id/members/:userId',async(req,res)=>{const id=String(req.params.id),userId=String(req.params.userId);await membership(id,req.user.id,false,true);const member=await membership(id,userId);if(member.role==='OWNER')throw new HttpError(422,'The owner cannot be removed.');await db.workspaceMember.delete({where:{workspaceId_userId:{workspaceId:id,userId}}});await revokeAccess(id,userId);res.status(204).end();});
  const fileSelect={id:true,name:true,type:true,parentId:true,workspaceId:true,updatedAt:true} as const;
  app.get('/api/workspaces/:id/files',async(req,res)=>{const id=String(req.params.id);await membership(id,req.user.id);res.json(await db.file.findMany({where:{workspaceId:id},select:fileSelect,orderBy:[{type:'desc'},{name:'asc'}]}));});
  app.post('/api/workspaces/:id/files',async(req,res)=>{const id=String(req.params.id);await membership(id,req.user.id,true);const data=fileSchema.parse(req.body);const file=await db.$transaction(async tx=>{if(data.parentId){const parent=await tx.file.findUnique({where:{id:data.parentId}});if(parent?.workspaceId!==id||parent.type!=='FOLDER')throw new HttpError(422,'Choose a folder in this workspace.');}if(await tx.file.count({where:{workspaceId:id}})>=100)throw new HttpError(422,'A workspace can contain up to 100 files and folders.');if(await tx.file.findFirst({where:{workspaceId:id,parentId:data.parentId,name:data.name}}))throw new HttpError(409,'A file with this name already exists here.');const result=await tx.file.create({data:{...data,workspaceId:id},select:fileSelect});await tx.workspace.update({where:{id},data:{updatedAt:new Date()}});return result;},{isolationLevel:'Serializable'});notifyFiles(id);res.status(201).json(file);});
  app.get('/api/files/:id',async(req,res)=>{const id=String(req.params.id);const file=await db.file.findUnique({where:{id}});if(!file)throw new HttpError(404,'File not found.');await membership(file.workspaceId,req.user.id);if(file.type==='FOLDER')throw new HttpError(422,'Select a file to open it.');const item=await loadDocument(id);res.json({...file,state:undefined,content:item.doc.getText('code').toString()});});
  app.patch('/api/files/:id',async(req,res)=>{const id=String(req.params.id);const file=await db.file.findUnique({where:{id}});if(!file)throw new HttpError(404,'File not found.');await membership(file.workspaceId,req.user.id,true);const {name}=z.object({name:filename}).parse(req.body);const updated=await db.$transaction(async tx=>{if(await tx.file.findFirst({where:{workspaceId:file.workspaceId,parentId:file.parentId,name,id:{not:id}}}))throw new HttpError(409,'That name is already in use.');return tx.file.update({where:{id},data:{name},select:fileSelect});},{isolationLevel:'Serializable'});notifyFiles(file.workspaceId);res.json(updated);});
  app.delete('/api/files/:id',async(req,res)=>{const id=String(req.params.id);const file=await db.file.findUnique({where:{id}});if(!file)throw new HttpError(404,'File not found.');await membership(file.workspaceId,req.user.id,true);const all=await db.file.findMany({where:{workspaceId:file.workspaceId},select:{id:true,parentId:true}});const deleted=new Set([id]);let previous=0;while(previous!==deleted.size){previous=deleted.size;for(const f of all)if(f.parentId&&deleted.has(f.parentId))deleted.add(f.id);}await discardDocuments([...deleted]);await db.file.delete({where:{id}});for(const fileId of deleted)io?.to(`file:${fileId}`).emit('file:deleted',{fileId});notifyFiles(file.workspaceId);res.status(204).end();});
  app.post('/api/files/:id/save',async(req,res)=>{const id=String(req.params.id);const file=await db.file.findUnique({where:{id}});if(!file)throw new HttpError(404,'File not found.');await membership(file.workspaceId,req.user.id,true);await flushDocument(id);res.json({saved:true});});
  app.get('/api/workspaces/:id/messages',async(req,res)=>{const id=String(req.params.id);await membership(id,req.user.id);res.json((await db.message.findMany({where:{workspaceId:id},take:100,orderBy:{createdAt:'desc'},include:{user:{select:{id:true,username:true,avatar:true}}}})).reverse());});
  app.post('/api/workspaces/:id/messages',async(req,res)=>{const id=String(req.params.id);await membership(id,req.user.id);const data=messageSchema.parse(req.body);const message=await db.message.create({data:{...data,workspaceId:id,userId:req.user.id},include:{user:{select:{id:true,username:true,avatar:true}}}});io?.to(`workspace:${id}`).emit('chat:message',message);res.status(201).json(message);});
  app.post('/api/files/:id/run',rateLimit({windowMs:60_000,limit:10}),async(req,res)=>{const id=String(req.params.id);const file=await db.file.findUnique({where:{id}});if(!file||file.type!=='FILE')throw new HttpError(404,'File not found.');await membership(file.workspaceId,req.user.id);const {stdin}=z.object({stdin:z.string().max(4000).default('')}).parse(req.body);const workspace=await db.workspace.findUniqueOrThrow({where:{id:file.workspaceId}});const item=await loadDocument(id);res.json(await execute(workspace.language,item.doc.getText('code').toString(),stdin));});
  app.use((_req,res)=>{res.status(404).json({error:'Endpoint not found.'});});
  app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{
    if(error instanceof ZodError){res.status(400).json({error:error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')});return;}
    if(error instanceof HttpError){res.status(error.status).json({error:error.message});return;}
    if(error instanceof Prisma.PrismaClientKnownRequestError){const status=error.code==='P2002'||error.code==='P2034'?409:error.code==='P2025'?404:500;res.status(status).json({error:status===409?'A conflicting change occurred. Try again or use a different name.':status===404?'This item no longer exists.':'Database operation failed. Please try again.'});return;}
    if(error instanceof Error && (error.name==='TimeoutError'||error.name==='AbortError')){res.status(504).json({error:'Code execution timed out.'});return;}
    console.error(error);res.status(500).json({error:'Unable to complete your request. Please try again.'});
  });
  return app;
}
