import { randomUUID } from 'node:crypto';
import bcrypt from 'bcryptjs';
import request from 'supertest';
import { afterAll, expect, test } from 'vitest';
import { createApp } from './app.js';
import { db } from './db.js';
import { config } from './config.js';
import { hashToken } from './auth.js';

// Uses the configured local database. Only this run's uniquely named accounts are removed.
const suffix = randomUUID().slice(0, 8);
const email = `phase2-${suffix}@example.com`;
const secondEmail = `phase2-other-${suffix}@example.com`;
const username = `phase2-${suffix}`;
const password = 'CodeSync-test-password';
const app = createApp();
afterAll(async () => {
  await db.user.deleteMany({ where: { email: { in: [email, secondEmail] } } });
  await db.$disconnect();
});

test('Phase 2 authentication, validation, session security, profile and logout', async () => {
  const agent = request.agent(app);
  expect((await agent.get('/api/auth/me')).status).toBe(401);
  expect((await agent.patch('/api/auth/me').set('Origin', config.WEB_ORIGIN).send({ username })).status).toBe(401);
  expect((await agent.post('/api/auth/register').send({ username, email, password })).status).toBe(403);
  expect((await agent.post('/api/auth/register').set('Origin', 'https://other.example').send({ username, email, password })).status).toBe(403);
  expect((await agent.post('/api/auth/register').set('Origin', config.WEB_ORIGIN).send({ username: 'x', email: 'bad', password: 'short' })).status).toBe(400);
  expect((await agent.post('/api/auth/register').set('Origin', config.WEB_ORIGIN).send({ username, email, password: '😀'.repeat(20) })).status).toBe(400);
  const registered = await agent.post('/api/auth/register').set('Origin', config.WEB_ORIGIN).send({ username, email: email.toUpperCase(), password });
  expect(registered.status).toBe(201);
  expect(registered.body.email).toBe(email);
  expect(registered.body.passwordHash).toBeUndefined();
  const cookie = String(registered.headers['set-cookie'][0]);
  expect(cookie).toContain('HttpOnly');
  expect(cookie).toContain(config.COOKIE_CROSS_SITE === 'true' ? 'SameSite=None' : 'SameSite=Lax');
  const raw = cookie.split(';')[0].split('=')[1];
  const account = await db.user.findUniqueOrThrow({ where: { email } });
  expect(account.passwordHash).not.toBe(password);
  expect(await bcrypt.compare(password, account.passwordHash)).toBe(true);
  const session = await db.session.findUniqueOrThrow({ where: { id: hashToken(raw) } });
  expect(session.id).not.toBe(raw);
  expect(session.expiresAt.getTime() - Date.now()).toBeGreaterThan(7 * 24 * 3600_000 - 60_000);
  expect(session.expiresAt.getTime() - Date.now()).toBeLessThanOrEqual(7 * 24 * 3600_000);
  const me = await agent.get('/api/auth/me');
  expect(me.status).toBe(200);
  expect(me.headers['cache-control']).toBe('no-store');
  expect(me.body.username).toBe(username);
  const protectedPage = await fetch(`${config.WEB_ORIGIN}/dashboard`, { redirect: 'manual' });
  expect(protectedPage.status).toBe(307);
  expect(protectedPage.headers.get('location')).toBe('/login');
  const dashboard = await fetch(`${config.WEB_ORIGIN}/dashboard`, { headers: { Cookie: `codesync_session=${raw}` } });
  expect(dashboard.status).toBe(200);
  const dashboardHtml = await dashboard.text();
  expect(dashboardHtml).toContain(username);
  expect(dashboardHtml).toContain(email);
  for (const path of ['/login', '/register']) {
    const authPage = await fetch(`${config.WEB_ORIGIN}${path}`, { redirect: 'manual', headers: { Cookie: `codesync_session=${raw}` } });
    expect(authPage.status).toBe(307);
    expect(authPage.headers.get('location')).toBe('/dashboard');
  }
  const duplicateEmail = await request(app).post('/api/auth/register').set('Origin', config.WEB_ORIGIN).send({ username: `${username}-new`, email, password });
  expect(duplicateEmail.status).toBe(409);
  expect(duplicateEmail.body.error).toContain('email');
  const duplicateName = await request(app).post('/api/auth/register').set('Origin', config.WEB_ORIGIN).send({ username, email: secondEmail, password });
  expect(duplicateName.status).toBe(409);
  expect(duplicateName.body.error).toContain('username');
  const second = await request(app).post('/api/auth/register').set('Origin', config.WEB_ORIGIN).send({ username: `${username}-other`, email: secondEmail, password });
  expect(second.status).toBe(201);
  expect((await agent.patch('/api/auth/me').set('Origin', config.WEB_ORIGIN).send({ username: `${username}-other` })).status).toBe(409);
  expect((await agent.patch('/api/auth/me').set('Origin', config.WEB_ORIGIN).send({ username: 'x' })).status).toBe(400);
  expect((await agent.patch('/api/auth/me').set('Origin', config.WEB_ORIGIN).send({ username: `${username}-updated` })).status).toBe(200);
  expect((await agent.get('/api/auth/me')).body.username).toBe(`${username}-updated`);
  expect((await agent.get('/api/workspaces')).body).toEqual([]);
  expect((await agent.post('/api/auth/logout').set('Origin', config.WEB_ORIGIN)).status).toBe(204);
  expect(await db.session.findUnique({ where: { id: hashToken(raw) } })).toBeNull();
  expect((await agent.get('/api/auth/me')).status).toBe(401);
  expect((await request(app).get('/api/auth/me').set('Cookie', `codesync_session=${raw}`)).status).toBe(401);
  const loggedOutPage = await fetch(`${config.WEB_ORIGIN}/dashboard`, { redirect: 'manual', headers: { Cookie: `codesync_session=${raw}` } });
  expect(loggedOutPage.status).toBe(307);
  expect(loggedOutPage.headers.get('location')).toBe('/login');
  expect((await agent.post('/api/auth/login').set('Origin', config.WEB_ORIGIN).send({ email, password: 'incorrect-password' })).status).toBe(401);
  expect((await agent.post('/api/auth/login').set('Origin', config.WEB_ORIGIN).send({ email: `missing-${email}`, password })).status).toBe(401);
  expect((await agent.post('/api/auth/login').set('Origin', config.WEB_ORIGIN).send({ email, password })).status).toBe(200);
  expect((await agent.get('/api/auth/me')).status).toBe(200);
  await db.session.updateMany({ where: { userId: account.id }, data: { expiresAt: new Date(Date.now() - 1000) } });
  expect((await agent.get('/api/auth/me')).status).toBe(401);
  expect((await request(app).get('/api/auth/me').set('Cookie', 'codesync_session=invalid')).status).toBe(401);
}, 90_000);
