import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { afterAll, expect, test } from 'vitest';
import { createApp } from './app.js';
import { db } from './db.js';
import { config } from './config.js';

const suffix = randomUUID().slice(0, 8);
const emails = [`phase4-a-${suffix}@example.com`, `phase4-b-${suffix}@example.com`];
const ids: string[] = [];
afterAll(async () => {
  await db.workspace.deleteMany({ where: { id: { in: ids } } });
  await db.user.deleteMany({ where: { email: { in: emails } } });
  await db.$disconnect();
});

test('file REST persistence, folders, conflicts, validation and role/access checks', async () => {
  const app = createApp(); const a = request.agent(app); const b = request.agent(app);
  const password = 'Phase4-test-password';
  const registeredA = await a.post('/api/auth/register').set('Origin', config.WEB_ORIGIN).send({ username: `phase4-a-${suffix}`, email: emails[0], password });
  const registeredB = await b.post('/api/auth/register').set('Origin', config.WEB_ORIGIN).send({ username: `phase4-b-${suffix}`, email: emails[1], password });
  expect(registeredA.status).toBe(201); expect(registeredB.status).toBe(201);
  const workspace = await a.post('/api/workspaces').set('Origin', config.WEB_ORIGIN).send({ name: `Files ${suffix}` });
  expect(workspace.status).toBe(201); const workspaceId = workspace.body.id; ids.push(workspaceId);
  const path = `/api/workspaces/${workspaceId}/files`;
  const create = (data: unknown) => a.post(path).set('Origin', config.WEB_ORIGIN).send(data);
  expect((await a.get(path)).body).toEqual([]);
  for (const name of ['', '   ', '.', '..', 'a/b.ts', '../a.ts', 'a\\b.ts', 'x'.repeat(101)]) expect((await create({ name })).status).toBe(400);
  expect((await create({ name: 'valid.ts', workspaceId: 'injected' })).status).toBe(400);
  const concurrent = await Promise.all([create({ name: 'same.ts' }), create({ name: 'same.ts' })]);
  expect(concurrent.map(response => response.status).sort()).toEqual([201, 409]);
  const root = await create({ name: ' index.ts ' }); expect(root.status).toBe(201); expect(root.body.name).toBe('index.ts');
  const id = root.body.id; const filePath = `/api/files/${id}`;
  const folder = await create({ name: 'src', type: 'FOLDER' }); expect(folder.status).toBe(201);
  const nested = await create({ name: 'index.ts', parentId: folder.body.id }); expect(nested.status).toBe(201);
  expect((await create({ name: 'index.ts', parentId: folder.body.id })).status).toBe(409);
  expect((await create({ name: 'inside.ts', parentId: id })).status).toBe(422);
  expect((await create({ name: 'inside.ts', parentId: 'invalid' })).status).toBe(400);
  const secondWorkspace = await a.post('/api/workspaces').set('Origin', config.WEB_ORIGIN).send({ name: `Other ${suffix}` }); ids.push(secondWorkspace.body.id);
  const foreignFolder = await a.post(`/api/workspaces/${secondWorkspace.body.id}/files`).set('Origin', config.WEB_ORIGIN).send({ name: 'foreign', type: 'FOLDER' });
  expect((await create({ name: 'inside.ts', parentId: foreignFolder.body.id })).status).toBe(422);
  expect((await a.get(`/api/files/${folder.body.id}`)).status).toBe(422);
  let loaded = await a.get(filePath); expect(loaded.body.content).toBe(''); expect(loaded.body.state).toBeUndefined(); expect(loaded.body.createdAt).toBeTruthy();
  const content = 'const message = "Hello, CodeSync";\nconsole.log(message);\n';
  const saved = await a.post(`${filePath}/save`).set('Origin', config.WEB_ORIGIN).send({ content, updatedAt: loaded.body.updatedAt });
  expect(saved.status).toBe(200); expect(saved.body.content).toBe(content);
  expect((await a.get(filePath)).body.content).toBe(content);
  expect((await db.file.findUniqueOrThrow({ where: { id } })).content).toBe(content);
  expect((await a.post(`${filePath}/save`).set('Origin', config.WEB_ORIGIN).send({ content: 'stale', updatedAt: loaded.body.updatedAt })).status).toBe(409);
  const renamed = await a.patch(filePath).set('Origin', config.WEB_ORIGIN).send({ name: 'app.ts', updatedAt: saved.body.updatedAt });
  expect(renamed.status).toBe(200); expect(renamed.body.name).toBe('app.ts'); expect(renamed.body.content).toBe(content);
  expect((await a.patch(filePath).set('Origin', config.WEB_ORIGIN).send({ name: 'same.ts' })).status).toBe(409);
  for (const payload of [{}, { name: '../bad.ts' }, { content: 'No version' }, { parentId: folder.body.id }, { workspaceId: secondWorkspace.body.id }, { content: 123, updatedAt: renamed.body.updatedAt }, { content: 'x'.repeat(200001), updatedAt: renamed.body.updatedAt }, { content: '漢'.repeat(70000), updatedAt: renamed.body.updatedAt }]) expect((await a.patch(filePath).set('Origin', config.WEB_ORIGIN).send(payload)).status).toBe(400);
  expect((await a.post(`${filePath}/save`).set('Origin', config.WEB_ORIGIN).send({ content: 'x'.repeat(320000), updatedAt: renamed.body.updatedAt })).status).toBe(413);
  expect((await a.post(`/api/files/${folder.body.id}/save`).set('Origin', config.WEB_ORIGIN).send({ content: 'code', updatedAt: folder.body.updatedAt })).status).toBe(422);
  expect((await a.post(`${filePath}/save`).set('Origin', 'https://other.example').send({ content: 'denied', updatedAt: renamed.body.updatedAt })).status).toBe(403);
  expect((await b.get(path)).status).toBe(403);
  expect((await b.post(path).set('Origin', config.WEB_ORIGIN).send({ name: 'denied.ts' })).status).toBe(403);
  for (const method of ['get', 'patch', 'delete'] as const) {
    expect((await b[method](filePath).set('Origin', config.WEB_ORIGIN).send(method === 'patch' ? { name: 'denied.ts' } : undefined)).status).toBe(403);
    expect((await request(app)[method](filePath).set('Origin', config.WEB_ORIGIN).send(method === 'patch' ? { name: 'denied.ts' } : undefined)).status).toBe(401);
    expect((await a[method]('/api/files/invalid').set('Origin', config.WEB_ORIGIN).send(method === 'patch' ? { name: 'denied.ts' } : undefined)).status).toBe(400);
    expect((await a[method]('/api/files/c000000000000000000000000').set('Origin', config.WEB_ORIGIN).send(method === 'patch' ? { name: 'denied.ts' } : undefined)).status).toBe(404);
  }
  expect((await b.post(`${filePath}/save`).set('Origin', config.WEB_ORIGIN).send({ content: 'denied', updatedAt: renamed.body.updatedAt })).status).toBe(403);
  await db.workspaceMember.create({ data: { workspaceId, userId: registeredB.body.id, role: 'VIEWER' } });
  expect((await b.get(filePath)).body.content).toBe(content);
  expect((await b.get(path)).status).toBe(200);
  expect((await b.post(path).set('Origin', config.WEB_ORIGIN).send({ name: 'denied.ts' })).status).toBe(403);
  expect((await b.patch(filePath).set('Origin', config.WEB_ORIGIN).send({ name: 'denied.ts' })).status).toBe(403);
  expect((await b.post(`${filePath}/save`).set('Origin', config.WEB_ORIGIN).send({ content: 'denied', updatedAt: renamed.body.updatedAt })).status).toBe(403);
  expect((await b.delete(filePath).set('Origin', config.WEB_ORIGIN)).status).toBe(403);
  await db.workspaceMember.update({ where: { workspaceId_userId: { workspaceId, userId: registeredB.body.id } }, data: { role: 'EDITOR' } });
  loaded = await b.get(filePath);
  expect((await b.patch(filePath).set('Origin', config.WEB_ORIGIN).send({ content: `${content}// editor save\n`, updatedAt: loaded.body.updatedAt })).status).toBe(200);
  expect((await a.post('/api/auth/logout').set('Origin', config.WEB_ORIGIN)).status).toBe(204);
  expect((await a.get(filePath)).status).toBe(401);
  expect((await a.post('/api/auth/login').set('Origin', config.WEB_ORIGIN).send({ email: emails[0], password })).status).toBe(200);
  expect((await a.get(filePath)).body.content).toBe(`${content}// editor save\n`);
  const subfolder = await create({ name: 'nested', type: 'FOLDER', parentId: folder.body.id });
  const descendant = await create({ name: 'main.py', parentId: subfolder.body.id });
  expect((await a.delete(`/api/files/${folder.body.id}`).set('Origin', config.WEB_ORIGIN)).status).toBe(204);
  for (const removedId of [folder.body.id, nested.body.id, subfolder.body.id, descendant.body.id]) expect(await db.file.findUnique({ where: { id: removedId } })).toBeNull();
  expect((await a.delete(filePath).set('Origin', config.WEB_ORIGIN)).status).toBe(204);
  expect((await a.get(filePath)).status).toBe(404);
  expect((await a.get(path)).body.some((file: { id: string }) => file.id === id)).toBe(false);
  await db.session.updateMany({ where: { userId: registeredA.body.id }, data: { expiresAt: new Date(Date.now() - 1000) } });
  expect((await a.get(path)).status).toBe(401);
}, 90_000);
